### ISSUE TITLE
Conf layer GEOGRAPHICALGRIDSYSTEMS.MAPS

### ISSUE THREAD

**Issue by viico** [IGNF/geoportal-configuration#2]
Bonjour,

IGN vient de communiquer la mise à dispo de la couche `GEOGRAPHICALGRIDSYSTEMS.MAPS` suite à leur migration. Nous utilisons cette couche.

Suite à la suppression de l'autoConf nous utilisons vos fichiers de conf, via le champ `apiKey` des options de la librairie. Sauf que je n'ai pas trouvé quel clef utilisé pour pouvoir utilisé cette couche. Avec la clef `cartes` nous avons bien des conf pour des couches tel que `GEOGRAPHICALGRIDSYSTEMS.MAPS.BDUNI.J1`, mais rien pour `GEOGRAPHICALGRIDSYSTEMS.MAPS`.

Pouvez-vous me renseigner sur comment récupérer la conf pour cette couche svp ?

Merci

**Comment by azarz** [comment]
Bonjour,

`GEOGRAPHICALGRIDSYSTEMS.MAPS` n'est pas une ressource ouverte, que ce soit sur l'ancienne infrastructure ou bien sur la Géoplateforme. Pour pouvoir l'interroger, il faudra créer une clef d'accès aux services Géoplateforme.

L'article suivant décrit plus précisément la situation : https://geoservices.ign.fr/actualites/2023-11-20-acces-donnesnonlibres-gpf

Si votre usage des données correspond aux conditions d'utilisations gratuites de ces données, conformément à la licence suivante : https://geoservices.ign.fr/cgu-licences, vous pouvez temporairement générer un fichier de configuration pour la clef `ign_scan_ws` à l'aide de l'interface suivante : https://geoplateforme-configuration.onrender.com/ ou bien directement via les scripts Python en local.

Cordialement,
